site_name:                    Infinity Framework
site_url:                     https://4x8matrix.github.io/
site_description:             API Documentation for the Infinity Framework

repo_url:                     https://github.com/4x8Matrix/InfinityFramework
repo_name:                    4x8Matrix/InfinityFramework

docs_dir:                     APIDocumentation

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - tables
  - admonition
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji

theme:
  name:                       material

  logo:                       SiteAssets/Icons/InfinityIcon.png
  favicon:                    SiteAssets/Icons/favicon.ico
  icon:
    repo:                     fontawesome/brands/git-alt

  font:
    text:                     Rubik

  features:
    - content.code.annotate
    - toc.integrate
    - navigation.tracking
    - search.suggest
    - search.highlight

  palette:
    - media:                  "(prefers-color-scheme: dark)"
      scheme:                 slate
      primary:                blue
      accent:                 light blue
      toggle:
        icon:                 material/toggle-switch-off-outline 
        name:                 Switch to light mode

    - media:                  "(prefers-color-scheme: light)"
      scheme:                 default
      primary:                blue
      accent:                 light blue
      toggle:
        icon:                 material/toggle-switch
        name:                 Switch to dark mode

nav:
  - Home:                     index.md
  - Installation:             InstallPage.md
  - Setup:                    SetupPage.md
  - Infinity:                 InfinityPage.md

  - Classes:
    - Network Class:          InfinityPages\InfinityClasses\NetworkClass.md
    - Private Class:          InfinityPages\InfinityClasses\PrivateClass.md
    - Public Class:           InfinityPages\InfinityClasses\PublicClass.md
    - Static Class:           InfinityPages\InfinityClasses\StaticClass.md
    - Base Class:             InfinityPages\InfinityClasses\BaseClass.md

  - Libaries:
    - Adornee:                InfinityPages\InfinityLibaries\AdorneeLibary.md
    - Hooks:                  InfinityPages\InfinityLibaries\HooksLibary.md
    - Iter:                   InfinityPages\InfinityLibaries\IterLibary.md
    - Maid:                   InfinityPages\InfinityLibaries\MaidLibary.md
    - Math:                   InfinityPages\InfinityLibaries\MathLibary.md
    - Net:                    InfinityPages\InfinityLibaries\NetLibary.md
    - Promise:                InfinityPages\InfinityLibaries\PromiseLibary.md
    - Proxy:                  InfinityPages\InfinityLibaries\ProxyLibary.md
    - Signal:                 InfinityPages\InfinityLibaries\SignalLibary.md
    - Watchdog:                 InfinityPages\InfinityLibaries\WatchdogLibary.md
    - State:                  InfinityPages\InfinityLibaries\StateLibary.md
    - Table:                  InfinityPages\InfinityLibaries\TableLibary.md
    - Timer:                  InfinityPages\InfinityLibaries\TimerLibary.md
    - Utils:                  InfinityPages\InfinityLibaries\UtilsLibary.md

  - Singletons:
    - Console:                InfinityPages\InfinitySingletons\InfinityConsole.md
    - Sound:                  InfinityPages\InfinitySingletons\InfinitySound.md
    - CoreGui:                InfinityPages\InfinitySingletons\InfinityCoreGui.md

extra:
  generator:                  false
  version:                    1.2

  social:
    - icon:                   fontawesome/brands/discord
      link:                   https://discord.gg/y6amckh
      name:                   Discord Community behind Infinity Framework!